spring:
  application:
    name: service-discovery
  config:
    import: "optional:configserver:${CONFIG-SERVER-URL}"

server:
  port: ${SERVER_PORT}

eureka:
  instance:
    hostname: ${HOSTNAME}
  client:
    register-with-eureka: false
    fetch-registry: false
